### ISSUE TITLE
Separate initialization from constructor

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet#18]
The initialization of things like fee rates and token addresses should be configured after the deployment in an `initialize()` method.

**Comment by mikeghen** [comment]
I did some work on this but this issue's still open because there's a much better job to be done that what I do in the StreamExchange constructor.

**Comment by josealonso** [comment]
I'll work on this.

**Comment by josealonso** [comment]
@mikeghen, I can see **UsingTellor** is a contract, not a modifier. Why don't you use the **is** keyword, then ?

**Comment by josealonso** [comment]
I replaced the **StreamExchange**'s constructor by an initialize() function, but I get a compiler error (locally) due to the **UsingTellor** base contract:
```TypeError: Contract "StreamExchange" should be marked as abstract.
  --> contracts/StreamExchange.sol:32:5:
   |
32 |     contract StreamExchange is Ownable, Initializable, SuperAppBase, UsingTellor {
   |     ^ (Relevant source part starts here and spans across multiple lines).
Note: Missing implementation: 
  --> contracts/tellor/UsingTellor.sol:19:5:
   |
19 |     constructor(address payable _tellor) {
   |     ^ (Relevant source part starts here and spans across multiple lines).


Error HH600: Compilation failed
```
Am I missing something ?

**Comment by josealonso** [comment]
It's compiling now. I thought I had to delete the constructor (hence the compilation errors above), but it has to delegate the initialization tasks to a different function. I only have to deploy it on Infura to see if it passes the tests. Pretty confident I will have it his week.

**Comment by mikeghen** [comment]
Thanks @josealonso! 👏
