### ISSUE TITLE
Dust collection

### ISSUE THREAD

**Issue by kobuta23** [Ricochet-Exchange/ricochet#2]
The function _exchange.ida.calculateDistribution effectively truncates the amount, because in the absence of float numbers, not all divisions are possible. 

So for example if you want to distribute 1000000001, and you have two units outstanding, then 1 will be lost. 

Based on current logic, all distributions are precise. However, this one isn't, leading to dust accumulating in the contract.

I suggest you change one of the functions to query and collect all existing balance rather than using a calculated figure. This could be either the feeCollected (governance gets the dust) or it could be calculateDistribution itself collecting the dust from the previous distribution.

https://github.com/mikeghen/rickoshea/blob/20dc9d416d117e418563bfe22c8eada6e6a88496/01-Contracts/contracts/StreamExchange.sol#L188

**Comment by mikeghen** [comment]
This was fixed, the contract uses `balanceOf()` instead of that method.
