### ISSUE TITLE
Save gas through unlimited approve

### ISSUE THREAD

**Issue by kobuta23** [Ricochet-Exchange/ricochet#3]
Could probably save some gwei on gas if the contract unlimited approved sushiswap and the Superfluid wrapper upfront, in the constructor. 

https://github.com/mikeghen/rickoshea/blob/20dc9d416d117e418563bfe22c8eada6e6a88496/01-Contracts/contracts/StreamExchange.sol#L256

**Comment by mikeghen** [comment]
Very good idea @kobuta23

**Comment by rashtrakoff** [comment]
Shouldn't this issue be closed ? I think here is the solution to this issue: 

https://github.com/Ricochet-Exchange/ricochet/blob/663ab38b16a52c306eb084fee6d09da0e88dc93e/01-Contracts/contracts/StreamExchange.sol#L88

**Comment by mikeghen** [comment]
Yes but its still open until this gets some test coverage
